import { FaWifi, FaCoffee, FaBath, FaParking, FaSwimmingPool, FaHotdog, FaStopwatch, FaCocktail } from 'react-icons/fa';
import images from '../assets';

export const roomData = [
  {
    id: 1,
    name: 'Superior Room',
    description:
      'More space, more comfort. Ideal for longer stays',
    facilities: [
      { name: 'Wifi', icon: FaWifi },
      { name: 'Restaurant', icon: FaCoffee },
      { name: 'Bath', icon: FaBath },
      { name: 'Parking Space', icon: FaParking },
      { name: 'Swimming Pool', icon: FaSwimmingPool },
      { name: 'Breakfast include', icon: FaHotdog },
      { name: 'GYM', icon: FaStopwatch },
      { name: 'Drinks', icon: FaCocktail },
    ],
    size: 276,
    maxPerson: 1,
    price: "2000+GST",
    image: images.Room1Img,
    imageLg: images.Room1ImgLg,
  },
  {
    id: 2,
    name: 'Executive King Room',
    description:
      'Separate seating + work desk. Great for CXOs & extended stays.',
    facilities: [
      { name: 'Wifi', icon: FaWifi },
      { name: 'Restaurant', icon: FaCoffee },
      { name: 'Bath', icon: FaBath },
      { name: 'Parking Space', icon: FaParking },
      { name: 'Swimming Pool', icon: FaSwimmingPool },
      { name: 'Breakfast include', icon: FaHotdog },
      { name: 'GYM', icon: FaStopwatch },
      { name: 'Drinks', icon: FaCocktail },
    ],
    size: 320,
    maxPerson: 4,
    price: "3000+GST",
    image: images.Room2Img,
    imageLg: images.Room2ImgLg,
  },
  {
    id: 3,
    name: 'Executive Twin Room',
    description:
      'A cozy choice with all essentials for business or leisure.',
    facilities: [
      { name: 'Wifi', icon: FaWifi },
      { name: 'Restaurant', icon: FaCoffee },
      { name: 'Bath', icon: FaBath },
      { name: 'Parking Space', icon: FaParking },
      { name: 'Swimming Pool', icon: FaSwimmingPool },
      { name: 'Breakfast include', icon: FaHotdog },
      { name: 'GYM', icon: FaStopwatch },
      { name: 'Drinks', icon: FaCocktail },
    ],
    size: 320,
    maxPerson: 3,
    price: "3000+GST",
    image: images.Room3Img,
    imageLg: images.Room3ImgLg,
  },
  {
    id: 4,
    name: 'Suite Room',
    description:
      'More space, more comfort. Ideal for longer stays',
    facilities: [
      { name: 'Wifi', icon: FaWifi },
      { name: 'Restaurant', icon: FaCoffee },
      { name: 'Bath', icon: FaBath },
      { name: 'Parking Space', icon: FaParking },
      { name: 'Swimming Pool', icon: FaSwimmingPool },
      { name: 'Breakfast include', icon: FaHotdog },
      { name: 'GYM', icon: FaStopwatch },
      { name: 'Drinks', icon: FaCocktail },
    ],
    size: 576,
    maxPerson: 4,
    price: "6000+GST",
    image: images.Room4Img,
    imageLg: images.Room4ImgLg,
  },
  {
    id: 5,
    name: 'Execuitive king Room',
    description:
      'Separate seating + work desk. Great for CXOs & extended stays.',
    facilities: [
      { name: 'Wifi', icon: FaWifi },
      { name: 'Restaurant', icon: FaCoffee },
      { name: 'Bath', icon: FaBath },
      { name: 'Parking Space', icon: FaParking },
      { name: 'Swimming Pool', icon: FaSwimmingPool },
      { name: 'Breakfast include', icon: FaHotdog },
      { name: 'GYM', icon: FaStopwatch },
      { name: 'Drinks', icon: FaCocktail },
    ],
    size: 320,
    maxPerson: 5,
    price: "3000+GST",
    image: images.Room5Img,
    imageLg: images.Room5ImgLg,
  },
  {
    id: 6,
    name: 'Executive Twin Room',
    description:
      'A cozy choice with all essentials for business or leisure.',
    facilities: [
      { name: 'Wifi', icon: FaWifi },
      { name: 'Restaurant', icon: FaCoffee },
      { name: 'Bath', icon: FaBath },
      { name: 'Parking Space', icon: FaParking },
      { name: 'Swimming Pool', icon: FaSwimmingPool },
      { name: 'Breakfast include', icon: FaHotdog },
      { name: 'GYM', icon: FaStopwatch },
      { name: 'Drinks', icon: FaCocktail },
    ],
    size: 320,
    maxPerson: 6,
    price: "3000+GST",
    image: images.Room6Img,
    imageLg: images.Room6ImgLg,
  },
  
];
